### ISSUE TITLE
Please clarify the license of your software

### ISSUE THREAD

**Issue by espresso-if** [UPPAALModelChecker/UDBM#8]
Hi,

can you please specify the license under which the library is released. So far I don't know whether I can you this library as an opensource lib or whether I have to ask for your permission.

Besides that do you plan to create a Java Binding?
I have seen that you have a Python binding using SWIG. As far as I understand it should be possible to create a java binding too.
That would be great.

Thank you in advance.

**Comment by yrke** [comment]
Hi 

Thanks for letting us know the LICENSE file was missing. It licensed as GLP3. 
The SWIG binding as currently not maintained. For Java binding i suggest having a look at J-Ecdar (https://github.com/Ecdar/j-Ecdar/tree/main/JCDD) and its JCDD lib (JCDD includes UDBM bindings). I expect at a later date that the java DBM/CDD binding will be moved to its own repo. 

Hope it helps

Regards, Kenneth

**Comment by espresso-if** [comment]
Yep.
Thank you.
(Sry for the late reply)
